### ISSUE TITLE
make docs

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/MuladdMacro.jl#25]

**Comment by devmotion** [comment]
Isn't it documented already in the SciML docs? https://docs.sciml.ai/stable/modules/MuladdMacro/

The package only defines `@muladd` and that is explained quite elaborately there it seems. The docstring is a bit shorter: https://github.com/SciML/MuladdMacro.jl/blob/4c936c1c9709deef2c82ca41ddf17edc4112ee57/src/MuladdMacro.jl#L23-L30

**Comment by devmotion** [comment]
I don't think this package will ever change, so this is a bit of a special case here. It has zero dependencies so also no other package can break it.

**Comment by ChrisRackauckas** [comment]
Yeah I'm not sure if this really needs a full docs, it's just one macro. The README seems fine for this one.
